### ISSUE TITLE
[Feature]: 未来那个版本适配RSTP

### ISSUE THREAD

**Issue by ThinkCodeStudio** [kendryte/k230_canmv#10]
### Feature description

硬件: 01studio k230
固件: 1.0.0
目前使用RSTP server demo 运行死机

**Comment by kendryte747** [comment]
目前计划在V1.2支持
大致版本规划
V1.1切到新的工程
V1.2用C重构meida 模块，Sensor Display Audio Video等，RTSP应该也会在这个版本一起重构

**Comment by ThinkCodeStudio** [comment]
有计划发布时间吗?

**Comment by kendryte747** [comment]
> 有计划发布时间吗?

https://github.com/canmv-k230/superproject_k230_rtsmart/releases/tag/PreRelease-dev 可以先试用这里的预览版固件

**Comment by kendryte747** [comment]
> 有计划发布时间吗?

https://github.com/kendryte/canmv_k230/releases/tag/v1.1 你好，1.1已发布

未来本仓库不再维护
