### ISSUE TITLE
[help]: aidemo库在哪里查看

### ISSUE THREAD

**Issue by ZuZuWithTaoTao** [kendryte/k230_canmv#2]
### Help

https://github.com/kendryte/k230_canmv/blob/main/tests/ai_demo/person_kp_detect.py
请问上面这个demo中import的aidemo库文件我可以在哪里查看到

**Comment by weiweijeff** [comment]
应该是在k230_canmv/tests文件夹里面

**Comment by JayL323** [comment]
ai demo的接口都在micropython_port/ai_demo中
