### ISSUE TITLE
[Bug]: I2C 2 无法打开

### ISSUE THREAD

**Issue by huayue0405** [kendryte/k230_canmv#3]
### What happened

代码
from machine import I2C
i2c4=I2C(2)

显示
can't open /dev/i2c  

### Reproduction steps

from machine import I2C
i2c4=I2C(2)

### Hardware board

k230 canmv

### Software version

micropython v0.4

### Bug frequency

all

### Anything else

问过群里，这个驱动没有编译，希望后续micropython版本添加上

**Comment by yixinghua121** [comment]
@huayue0405 micropython v0.5 version，驱动已加入I2C2

**Comment by wuwentao** [comment]
当前issue长时间为收到响应或回复，先close了。
如果仍有问题，或者需要继续沟通，仍然可以reopen当前issue。
