### ISSUE TITLE
[help]: Communication between cores

### ISSUE THREAD

**Issue by Ben01233210** [kendryte/k230_canmv#6]
### Help

Hey,
I used the c sdk a bit and came across the ipcmsg module and found it pretty useful. But to speed up development times I wanted to switch to micropython. I was wondering if it is possible to run one the big core micropython and on the small core c? And if it is possible is it planned to implement datafifo and ipcmsg in micropython?

**Comment by zhaohu5188** [comment]
And if it is possible is it planned to implement datafifo and ipcmsg in micropython?
==>  There are no plans for that at the moment
